# Generated by Django 5.2 on 2025-09-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applicationreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jobs.jobapplication'),
        ),
    ]
