# Generated by Django 5.2 on 2025-10-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_applicationreview_application'),
        ('users', '0005_remove_employerprofile_linked_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationreview',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication'),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='employer_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile'),
        ),
    ]
