# Generated by Django 5.2 on 2025-11-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_applicationreview_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
