# Generated by Django 5.2 on 2025-11-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreview',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
