# Generated by Django 5.2 on 2025-11-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_applicationreview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending Review', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Offer Made', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending Review', max_length=14),
        ),
    ]
